name: CI

on:
  push:
    branches:
      - master
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: 'true'
          submodules: 'false'
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: '.'
          exclude: './external'

  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [debug, release]

    steps:
    - uses: actions/checkout@v2
      with:
        clean: 'true'
        submodules: 'true'

    - name: Add nuget to PATH
      uses: nuget/setup-nuget@v1

    - name: Premake
      run: .\premake.bat

    - name: Restore NuGet packages for codegen
      run: nuget restore build\heart-engine-playground.sln

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild build\heart-engine-playground.sln -m /p:platform=x64 /p:configuration=${{ matrix.config }}

    - name: Unit Tests
      run: build/bin/heart-test/${{ matrix.config }}/heart-test.exe

    - name: Run
      run: build/bin/sfml-demo/${{ matrix.config }}/sfml-demo.exe --framecount 60

    - name: Upload heartgen result
      uses: actions/upload-artifact@v1
      with:
        name: heartgen-output
        path: game/src/gen/reflection.heartgen.cpp
