# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-win"
  build-win:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        clean: 'true'
        submodules: 'false'

    - name: Checkout submodules
      run: |
        git submodule update --init external/entt
        git submodule update --init external/imgui
        git submodule update --init external/imgui-sfml
        git submodule update --init external/rapidjson
        git submodule update --init external/sfml
        git submodule update --init external/smhasher
        git submodule update --init external/tweeny

    - name: Add nuget to PATH
      uses: nuget/setup-nuget@v1

    - name: Premake
      run: .\premake.bat --boostlib=$Env:BOOST_ROOT_1_72_0

    - name: Restore NuGet packages for codegen
      run: nuget restore build\heart-engine-playground.sln

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build debug
      run: msbuild build\heart-engine-playground.sln -m /p:platform=x64 /p:configuration=debug

    - name: Build release
      run: msbuild build\heart-engine-playground.sln -m /p:platform=x64 /p:configuration=release

    - name: Upload heartgen result
      uses: actions/upload-artifact@v1
      with:
        name: heartgen-output
        path: game/src/gen/reflection.heartgen.cpp
